create table if not exists public.product_pricing (
  id bigint generated by default as identity primary key,
  product_slug text not null unique,
  product_name text not null,
  order_mode text not null default 'quote' check (order_mode in ('quote','online')),
  setup numeric(12,2) not null default 0,
  sqft_rate numeric(12,2) not null default 0,
  unit_rate numeric(12,2) not null default 0,
  minimum numeric(12,2) not null default 0,
  currency text not null default 'USD',
  is_active boolean not null default true,
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.product_pricing enable row level security;
