create table if not exists public.product_pricing (
  id bigint generated by default as identity primary key,
  product_slug text not null unique,
  product_name text not null,
  order_mode text not null default 'quote' check (order_mode in ('quote','online')),
  setup numeric(12,2) not null default 0,
  sqft_rate numeric(12,2) not null default 0,
  unit_rate numeric(12,2) not null default 0,
  minimum numeric(12,2) not null default 0,
  currency text not null default 'USD',
  is_active boolean not null default true,
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.product_pricing enable row level security;

create table if not exists public.square_oauth_states (
  id bigint generated by default as identity primary key,
  state text not null unique,
  admin_user_id uuid references auth.users(id),
  admin_email text,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.square_oauth_states enable row level security;

create table if not exists public.square_connections (
  id bigint generated by default as identity primary key,
  connection_key text not null unique default 'primary',
  merchant_id text not null,
  merchant_name text,
  environment text not null default 'sandbox',
  access_token_encrypted text not null,
  refresh_token_encrypted text not null,
  token_expires_at timestamptz,
  scopes jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  connected_by uuid references auth.users(id),
  connected_at timestamptz not null default now(),
  disconnected_at timestamptz,
  updated_at timestamptz not null default now()
);
alter table public.square_connections enable row level security;
